- name: Install Docker and Docker Swarm
  hosts: docker_nodes
  become: true
  serial: 1 #needed because I am running multiple nodes on the same host 
  vars_files:
    - variables/docker_vars.yaml 
  tasks:

    - name: Install pip
      ansible.builtin.apt:
        name: ["python3-dev", "python3-setuptools", "python3-pip"]
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Update pip
      ansible.builtin.pip:
        name: ["pip", "openstacksdk"]
        state: latest

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Start Docker Engine
      systemd:
        name: docker
        state: started

- name: Initialize the swarm 
  hosts: all
  become: true
  vars_files:
    - variables/docker_vars.yaml 
  tasks:
    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        name: "default"
        state: present
      when: inventory_hostname == groups['swarm_managers'] | first


    - name: Get the Manager join-token
      shell: docker swarm join-token --quiet manager
      register: manager_token

    - name: Get the worker join-token
      shell: docker swarm join-token --quiet worker
      register: worker_token

    - name: Add manager nodes to the swarm
      community.docker.docker_swarm:
        state: join
        advertise_addr: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        join_token: "{{ manager_token.stdout }}"
        remote_addrs: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}:2377"
      loop: "{{ groups['swarm_managers'] }}"  

    - name: Add worker nodes to the swarm
      community.docker.docker_swarm:
        state: join
        #advertise_addr: "{{ ansible_host }}" #might not be needed 
        join_token: "{{ worker_token.stdout }}"
        remote_addrs: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}:2377"
      loop: "{{ groups['swarm_workers'] }}"


